export type FlexWrapOption = 'nowrap' | 'wrap' | 'wrap-reverse'
export type FlexDirectionOption = 'row' | 'row-reverse' | 'column' | 'column-reverse'
export type AlignItemsOption = 'normal' | 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch' | 'unset'
export type JustifyContentOption = 'normal' | 'flex-start' | 'flex-end' | 'center' | 'space-between' | 'space-around' | 'space-evenly'
export type OverflowOption = 'visible' | 'hidden' | 'scroll' | 'auto' | 'clip'
export type OverscrollBehaviorOption = 'auto' | 'contain' | 'none'
export type TextAlignOption = 'left' | 'right' | 'center' | 'justify' | 'initial' | 'inherit'
export type CursorOption =
  | 'auto'
  | 'default'
  | 'none'
  | 'context-menu'
  | 'help'
  | 'pointer'
  | 'progress'
  | 'wait'
  | 'cell'
  | 'crosshair'
  | 'text'
  | 'vertical-text'
  | 'alias'
  | 'copy'
  | 'move'
  | 'no-drop'
  | 'not-allowed'
  | 'grab'
  | 'grabbing'
  | 'all-scroll'
  | 'col-resize'
  | 'row-resize'
  | 'n-resize'
  | 'e-resize'
  | 's-resize'
  | 'w-resize'
  | 'ne-resize'
  | 'nw-resize'
  | 'se-resize'
  | 'sw-resize'
  | 'ew-resize'
  | 'ns-resize'
  | 'nesw-resize'
  | 'nwse-resize'
  | 'zoom-in'
  | 'zoom-out'
